### ISSUE TITLE
TKInter assert error

### ISSUE THREAD

**Issue by step21** [Hack-a-Day/2022-Supercon6-Badge-Tools#44]
Hey,

somehow I always get a TKInter assert error on the emulator.

```
AND: {'mode': 1, 'n': 3}
CP: {'n': 0}
CP: {'n': 3}
CP: {'n': 0}
ADD: {'mode': 1, 'n': 6}
CP: {'n': 0}
CP: {'n': 10}
CP: {'n': 0}
ADD: {'mode': 1, 'n': 14}
CP: {'n': 0}
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 839, in callit
    func(*args)
  File "/home/user/2022-Supercon6-Badge-Tools/emulator/bvm.py", line 107, in runtimeTasks
    self.badge.update()
  File "/home/user/2022-Supercon6-Badge-Tools/emulator/badge.py", line 102, in update
    self.step()
  File "/home/user/2022-Supercon6-Badge-Tools/emulator/badge.py", line 81, in step
    instruction = parse(raw_instr)
  File "/home/user/2022-Supercon6-Badge-Tools/emulator/bvmParser.py", line 24, in parse
    assert(padding==0)
AssertionError

Traceback (most recent call last):
  File "/home/user/2022-Supercon6-Badge-Tools/emulator/bvm.py", line 311, in <module>
    bvm.run()
  File "/home/user/2022-Supercon6-Badge-Tools/emulator/bvm.py", line 122, in run
    self.window.mainloop()
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1458, in mainloop
    self.tk.mainloop(n)
```

I tried this under both macOS and Linux, with different versions of Python, and the same error all times. I would have to check the exact versions of tkinter, but one was the newest available from homebrew, the other was the one shipped with PopOS 22.04.

Any hints welcome.

**Comment by monolied** [comment]
Probably the bin file you're using... try one of the examples?

**Comment by monolied** [comment]
I had the same (or very similar) issue when I was using some arbitrary binary file for a test. Probably anything you throw at the emulator gets interpreted as a sequence of machine code, and in these cases it's not a surprise when the length of the file is odd (one in three chance, I guess, without looking at the compiler) and JUMPs and RETs don't match.
If it was indeed a compiled example, it would be interesting to know the specific example, compare the .bin files on both machines and/or know other differences of the machines... but if everything is fine now, maybe that's good enough.
